export const authConstants = {
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};

export const userConstants = {
  CREATEUSER_FAILURE: "CREATEUSER_FAILURE",
  CREATEUSER_SUCCESS: "CREATEUSER_SUCCESS",
  GETUSER_SUCCESS: "GETUSER_SUCCESS",
  USER_AUTHDETAILS: "USER_AUTHDETAILS",
  GETUSER_FAILURE: "GETUSER_FAILURE",
  REQUEST: "REQUEST",
  UPDATE_USERAUTHDETAILS: "UPDATE_USERAUTHDETAILS",
  UPDATE_USERAUTHDETAILS_FAILURE: "UPDATE_USERAUTHDETAILS_FAILURE",
  UPDATE_USERCATALOGUE: "UPDATE_USERCATALOGUE",
  UPDATE_USERCATALOGUE_FAILURE: "UPDATE_USERCATALOGUE_FAILURE",
  USER_CLEAR_AUTHDETAILS: "USER_CLEAR_AUTHDETAILS",
};

export const adConstants = {
  GETPOSTS_FAILURE: "GETADS_FAILURE",
  GETPOSTS_SUCCESS: "GETPOSTS_SUCCESS",
  GETUSERPOSTS_SUCCESS: "GETUSERPOSTS_SUCCESS",
  DELETEPOST_SUCCESS: "DELETEPOST_SUCCESS",
  DELETEPOST_FAILURE: "DELETEPOST_FAILURE",
  GETAD_SUCCESS: "GETAD_SUCCESS",
  GETAD_FAILURE: "GETAD_FAILURE",
  SETIMGARRAY: "SETIMGARRAY",
  CLEARIMGARRAY: "CLEARIMGARRAY",
  POSTAD_REQUEST: "POSTAD_REQUEST",
  POSTAD_SUCCESS: "POSTAD_SUCCESS",
  POSTAD_FAILURE: "POSTAD_FAILURE",
  GETAPPROVEDADS_SUCCESS: "GETAPPROVEDADS_SUCCESS",
  GETAPPROVEDADS_FAILURE: "GETAPPROVEDADS_FAILURE",
  UPDATEPOST_SUCCESS: "UPDATEPOST_SUCCESS",
  UPDATEPOST_FAILURE: "UPDATEPOST_FAILURE",
  GETCATALOGUE_SUCCESS: "GETCATALOGUE_SUCCESS",
  GETCATALOGUE_FAILURE: "GETCATALOGUE_FAILURE",
  BUY_STATUS: "BUY_STATUS",
  BUY_FAILURE: "BUY_FAILURE",
  REQUEST: "REQUEST",
  RESET_AD_UNMOUNT: "RESET_AD_UNMOUNT",
  RESET_USER_AD_DETAILS: "RESET_USER_AD_DETAILS",
};

export const commentConstants = {
  POSTCOMMENT_FAILURE: "POSTCOMMENT_FAILURE",
  POSTCOMMENT_SUCCESS: "POSTCOMMENT_SUCCESS",
  GETCOMMENTS_SUCCESS: "GETCOMMENTS_SUCCESS",
  RESET_COMMENTS_UNMOUNT: "RESET_COMMENTS_UNMOUNT",
};

export const filterConstants = {
  SETFILTER: "SETFILTER",
};
